import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./shared/Header/Header";
import DashboardHeader from "@/components/DashboardHeader";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex flex-col ">
          <div>
            <Header />
          </div>
          <div className="flex gap-5  py-6 px-4 xl:px-10 h-screen overflow-y-auto bg-[#8aa7d6]">
            <div className="bg-[#b6c5dd] w-[300px] hidden xl:block rounded-2xl p-2.5">
              {" "}
              <Sidebar />
            </div>
            <div className=" w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
